ci:
  image: vibioh/ci:latest
  labels:
    io.rancher.sidekicks: jenkins
  volumes:
    - ${CI_DIR}/jenkins:/var/jenkins_home
  read_only: true
  restart: 'no'
  cpu_shares: 128
  mem_limit: 67108864
jenkins:
  image: jenkins:latest
  labels:
    traefik.port: '8080'
    traefik.frontend.rule: 'Host'
    traefik.frontend.value: 'jenkins.${DOMAIN}'
    traefik.frontend.passHostHeader: 'true'
  volumes_from:
    - ci
  restart: 'no'
  cpu_shares: 512
  mem_limit: 1073741824