ci:
  image: vibioh/ci:latest
  labels:
    io.rancher.sidekicks: jenkins, mysql, sonar
  restart: 'no'
  read_only: true
  cpu_shares: 128
  mem_limit: 67108864
jenkins:
  image: jenkins:latest
  labels:
    traefik.port: '8080'
    traefik.frontend.rule: 'Host'
    traefik.frontend.value: 'jenkins.${DOMAIN}'
    traefik.frontend.passHostHeader: 'true'
  volumes_from:
    - ci
  restart: 'no'
  cpu_shares: 512
  mem_limit: 1073741824
sonar:
  image: sonarqube:latest
  links:
    - mysql
  environment:
    - SONARQUBE_JDBC_USERNAME=sonar
    - SONARQUBE_JDBC_PASSWORD=sonar
    - SONARQUBE_JDBC_URL=jdbc:mysql://mysql/sonar?useUnicode=true&characterEncoding=utf8
  labels:
    traefik.port: '9000'
    traefik.frontend.rule: 'Host'
    traefik.frontend.value: 'sonar.${DOMAIN}'
    traefik.frontend.passHostHeader: 'true'
  volumes_from:
    - ci
  restart: 'no'
  cpu_shares: 512
  mem_limit: 536870912
mysql:
  image: vibioh/mysql:latest
  environment:
    - MYSQL_ROOT_PASSWORD=s3Cr3T!
    - MYSQL_DATABASE=sonar
    - MYSQL_USER=sonar
    - MYSQL_PASSWORD=sonar
  labels:
    traefik.enable: false
  volumes_from:
    - ci
  restart: 'no'
  read_only: true
  cpu_shares: 512
  mem_limit: 268435456