ci:
  image: vibioh/ci:latest
  labels:
    io.rancher.sidekicks: jenkins, postgres, sonar
  volumes:
    - ${CI_DIR}/jenkins:/var/jenkins_home
    - ${CI_DIR}/postgres:/var/lib/postgresql/data
  read_only: true
  restart: 'no'
  cpu_shares: 128
  mem_limit: 67108864
jenkins:
  image: jenkins:latest
  labels:
    traefik.port: '8080'
    traefik.frontend.rule: 'Host'
    traefik.frontend.value: 'jenkins.${DOMAIN}'
    traefik.frontend.passHostHeader: 'true'
  volumes_from:
    - ci
  restart: 'no'
  cpu_shares: 512
  mem_limit: 1073741824
sonar:
  image: sonarqube:latest
  links:
    - postgres
  environment:
    - SONARQUBE_JDBC_USERNAME=sonar
    - SONARQUBE_JDBC_PASSWORD=sonar
    - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/sonar?useUnicode=true&characterEncoding=utf8
  labels:
    traefik.port: '9000'
    traefik.frontend.rule: 'Host'
    traefik.frontend.value: 'sonar.${DOMAIN}'
    traefik.frontend.passHostHeader: 'true'
  volumes_from:
    - ci
  restart: 'no'
  cpu_shares: 512
  mem_limit: 536870912
postgres:
  image: vibioh/postgres:latest
  environment:
    - POSTGRES_DB=sonar
    - POSTGRES_USER=sonar
    - POSTGRES_PASSWORD=sonar
  labels:
    traefik.enable: 'false'
  volumes_from:
    - ci
  read_only: true
  restart: 'no'
  cpu_shares: 512
  mem_limit: 268435456
