traefik:
  image: emilevauge/traefik:latest
  ports:
  - 80:80/tcp
  labels:
    traefik.port: '8080'
    traefik.frontend.rule: 'Host'
    traefik.frontend.value: 'traefik.vibioh.fr'
    traefik.frontend.passHostHeader: 'true'
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  - /var/traefik/traefik.toml:/traefik.toml
  cpu_shares: 256
  mem_limit: 134217728