traefik:
  image: emilevauge/traefik:latest
  ports:
  - 80:${LISTEN_PORT}/tcp
  labels:
    traefik.port: '${WEB_PORT}'
    traefik.frontend.rule: 'Host'
    traefik.frontend.value: 'traefik.${DOMAIN}'
    traefik.frontend.passHostHeader: 'true'
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  - /var/traefik/traefik.toml:/traefik.toml
  restart: 'no'
  cpu_shares: 256
  mem_limit: 134217728