.catalog:
  name: Jenkins
  version: latest
  description: Jenkins Continuous Integration
  uuid: jenkins-0
  questions:
  - variable: 'DOMAIN'
    description: 'Domain name'
    label: 'Domain:'
    required: true
    default: 'vibioh.fr'
    type: 'string'
  - variable: 'JENKINS_DIR'
    description: 'Working directory path for Jenkins'
    label: 'Jenkins dir:'
    required: true
    default: '/var/ci/jenkins'
    type: 'string'
  - variable: 'SONAR_DIR'
    description: 'Working directory path for Sonar'
    label: 'Sonar dir:'
    required: true
    default: '/var/ci/sonar'
    type: 'string'
jenkins:
  scale: 1
sonar:
  scale: 1
mysql:
  scale: 1