rabbitmq:
  image: rabbitmq:3-management
  ports:
  - 5672:5672/tcp
  labels:
    traefik.frontend.passHostHeader: 'true'
    traefik.frontend.rule: 'Host'
    traefik.frontend.value: 'rabbit.${DOMAIN}'
    traefik.port: '15672'
  hostname: rabbitmq
  cpu_shares: 512
  mem_limit: 536870912
